name: proteinflex-test-core
channels:
  - conda-forge
  - defaults
dependencies:
  # Core dependencies
  - python=3.10
  - pip
  - setuptools
  - wheel
  - cython=3.0.11
  - numpy=1.24.4
  - scipy=1.9.3
  - pandas=2.0.3
  - biopython=1.84
  - biotite=0.38.0
  - openmm=8.0.0
  - mdtraj=1.9.7
  - prody=2.4.1
  - pytest
  - pytest-cov
  - coverage
  - flake8

  - pip:
    # Deep learning dependencies
    - torch==2.0.1 --extra-index-url https://download.pytorch.org/whl/cpu
    - transformers==4.32.0
    - google-cloud-aiplatform==1.35.0

    # Testing dependencies
    - pytest-mock==3.12.0
    - pytest-asyncio==0.23.5
    - pytest-timeout==2.2.0
    - pytest-xdist==3.5.0
    - coverage-badge==1.1.0
    - mock==5.1.0
    - pytest-env==1.1.3
    - pytest-randomly==3.15.0

    # Install package in editable mode
    - -e .
