name: proteinflex-env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python and build tools only
  - python=3.8
  - pip
  - setuptools
  - wheel
  - make
  - cmake
  - gcc
  - gxx
  - pkg-config
  - cython=0.29.32

  - pip:
    # Scientific dependencies
    - numpy==1.23.5
    - scipy==1.9.3
    - pandas==1.5.3
    - matplotlib==3.6.2
    - biopython==1.80

    # Bioinformatics dependencies
    - mdtraj==1.9.7
    - openmm==7.7.0
    - prody==2.0.0

    # Deep learning dependencies
    - torch==1.13.1+cpu --extra-index-url https://download.pytorch.org/whl/cpu
    - transformers==4.25.1
    - tokenizers==0.13.2

    # Testing dependencies
    - pytest==7.1.2
    - pytest-cov==3.0.0
    - coverage==6.5.0
    - flake8==5.0.4
    - pytest-mock==3.10.0
    - pytest-asyncio==0.20.3
    - pytest-timeout==2.1.0
    - pytest-xdist==3.1.0
    - mock==5.0.1
    - pytest-env==0.8.1
    - pytest-randomly==3.12.0
    - coverage-badge==1.1.0

    # Additional dependencies
    - google-cloud-aiplatform==1.21.0

    # Install package in editable mode
    - -e .
