name: proteinflex-test-core
channels:
  - conda-forge
  - defaults
dependencies:
  # Build dependencies
  - make
  - cmake
  - gcc
  - gxx
  - pkg-config

  # Core dependencies
  - python=3.10
  - pip
  - setuptools
  - wheel
  - cython=3.0.11

  # Scientific computation (pre-built packages)
  - numpy=1.24.4
  - scipy=1.9.3
  - pandas=2.0.3
  - biopython=1.84
  - biotite=0.38.0
  - openmm=8.0.0
  - mdtraj=1.9.7
  - prody=2.4.1

  # Testing dependencies
  - pytest
  - pytest-cov
  - coverage
  - flake8
  - pytest-mock
  - pytest-asyncio
  - pytest-timeout
  - pytest-xdist
  - mock
  - pytest-env
  - pytest-randomly

  - pip:
    # Deep learning dependencies (CPU only)
    - torch==2.0.1 --extra-index-url https://download.pytorch.org/whl/cpu
    - transformers==4.32.0
    - google-cloud-aiplatform==1.35.0
    - coverage-badge==1.1.0

    # Install package in editable mode (after all dependencies)
    - -e .
