name: proteinflex-env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.10
  - pip
  - setuptools
  - wheel

  # Build dependencies
  - make
  - cmake
  - gcc
  - gxx
  - pkg-config
  - cython=0.29.36

  # Core scientific dependencies
  - numpy>=1.24,<1.25
  - scipy>=1.9
  - pandas>=1.5
  - matplotlib-base>=3.7

  # Bioinformatics dependencies
  - biopython>=1.81
  - mdtraj>=1.9.7
  - openmm>=7.7.0
  - prody>=2.4.0

  # Development dependencies
  - pytest>=7.0
  - pytest-cov
  - coverage
  - flake8

  # Deep learning dependencies
  - pytorch::pytorch-cpu
  - transformers>=4.32.0

  - pip:
    # Additional dependencies
    - google-cloud-aiplatform>=1.35.0

    # Testing dependencies
    - pytest-mock>=3.12.0
    - pytest-asyncio>=0.23.5
    - pytest-timeout>=2.2.0
    - pytest-xdist>=3.5.0
    - mock>=5.1.0
    - pytest-env>=1.1.3
    - pytest-randomly>=3.15.0
    - coverage-badge>=1.1.0

  # Install package in editable mode
  - pip:
    - -e .
