name: proteinflex-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.10.12
  - pip=23.3.1
  - setuptools=68.2.2
  - wheel=0.41.2

  # Build dependencies
  - make
  - cmake
  - gcc=11.4
  - gxx=11.4
  - pkg-config
  - cython=0.29.36

  # System libraries
  - zlib=1.3.1
  - bzip2=1.0.8
  - xz=5.2.6
  - hdf5=1.14.4
  - netcdf4=1.6.5
  - fftw=3.3.10
  - boost=1.82.0
  - libboost=1.82.0
  - libxml2=2.12.5
  - libxslt=1.1.39

  # Core scientific dependencies
  - numpy=1.24.4
  - scipy=1.10.1
  - pandas=2.0.3
  - matplotlib-base=3.9.2

  # Bioinformatics dependencies
  - biopython=1.84
  - biotite=0.38.0
  - mdtraj=1.9.7
  - openmm=7.7.0
  - parmed=3.4.3
  - prody=2.4.0  # Downgraded to work with numpy 1.24.4

  # Development dependencies
  - pytest=7.4.3  # Downgraded for better compatibility
  - pytest-cov=4.1.0
  - coverage=7.3.2
  - flake8=6.1.0

  # Deep learning dependencies
  - pytorch=2.0.1
  - cpuonly
  - transformers=4.32.0

  - pip:
    # Additional dependencies
    - google-cloud-aiplatform==1.35.0
    - coverage-badge==1.1.0

    # Testing dependencies
    - pytest-mock==3.12.0
    - pytest-asyncio==0.23.5
    - pytest-timeout==2.2.0
    - pytest-xdist==3.5.0
    - mock==5.1.0
    - pytest-env==1.1.3
    - pytest-randomly==3.15.0

  # Install package in editable mode
  - pip:
    - -e .
