name: proteinflex-test-core
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9
  - pip
  - setuptools
  - wheel

  # Build dependencies
  - make
  - cmake
  - gcc
  - gxx
  - pkg-config
  - swig
  - fftw
  - hdf5
  - netcdf4
  - cython=3.0.11

  # Scientific computation base
  - numpy=1.23.5
  - scipy=1.9.3
  - pandas=1.5.3

  # Bioinformatics
  - biopython=1.80
  - biotite=0.38.0
  - openmm=7.7.0
  - mdtraj=1.9.7
  - prody=2.4.1

  # Testing dependencies
  - pytest
  - pytest-cov
  - coverage
  - flake8
  - pytest-mock
  - pytest-asyncio
  - pytest-timeout
  - pytest-xdist
  - mock
  - pytest-env
  - pytest-randomly

  # Deep learning (CPU only)
  - pytorch::pytorch=1.13.1=cpu
  - transformers=4.32.0

  - pip:
    # Additional packages
    - google-cloud-aiplatform==1.35.0
    - coverage-badge==1.1.0

    # Install package in editable mode (after all dependencies)
    - -e .
