name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch>=2.0.0 numpy>=1.21.0 scipy>=1.10.0 pandas>=2.0.0 scikit-learn>=1.2.0 biopython>=1.79 mdtraj>=1.9.7 prody>=2.4.0 biotite>=0.35.0 plotly>=5.13.0 py3dmol>=1.8.0 flask>=2.0.1 transformers>=4.30.0 datasets>=2.12.0 tokenizers>=0.13.0 tqdm>=4.65.0 requests>=2.31.0 openmm>=8.0.0 fair-esm>=2.0.0

    - name: Lint code
      run: |
        pip install flake8
        flake8 src tests

    - name: Run tests
      run: |
        pip install pytest
        pytest
